// ─── CANONICAL LONG RESEARCH SCHEMA VERSIONS ─────────────────────────────────
// Single source of truth for every LongLAB research/export/runtime version.

export const LONG_ENTRY_RESEARCH_SCHEMA_VERSION = 'LONG_ENTRY_RESEARCH_V9';
export const LONG_FILTER_SNAPSHOT_VERSION = 'LONG_FILTER_SNAPSHOT_V9';
export const LONG_TRADE_EXPORT_VERSION = 'LONG_TRADE_EXPORT_V9';

export const LONG_SCORE_REGISTRY_VERSION = 'LONG_SCORE_REGISTRY_V7_2026_06';
export const LONG_FILTER_REGISTRY_VERSION = 'LONG_FILTER_REGISTRY_V7_2026_06';
export const LONG_LABEL_REGISTRY_VERSION = 'LONG_LABEL_REGISTRY_V7_2026_06';
export const LONG_COMBO_REGISTRY_SCHEMA_VERSION = 'LONG_COMBO_REGISTRY_SCHEMA_V4_2026_06';
export const LONG_TICK_DIRECTION_VERSION = 'LONG_TICK_DIRECTION_V1_2026_06';
export const LONG_ANTI_COMBO_REGISTRY_VERSION = 'LONG_ANTI_COMBO_REGISTRY_V2_2026_06';
export const LONG_WINNING_SETUP_REGISTRY_VERSION = 'LONG_WINNING_SETUPS_V2_2026_06';
export const LONG_MARKET_CONTEXT_VERSION = 'LONG_MARKET_CONTEXT_V2_2026_06';
export const LONG_EXIT_SYSTEM_VERSION = 'LONG_EXIT_SYSTEM_V4_2026_06';
export const LONG_FEE_MODEL_VERSION = 'LONG_FEE_MODEL_V2_2026_06';
export const LONG_PNL_MODEL_VERSION = 'LONG_PNL_MODEL_V2_2026_06';

export const LONG_RESEARCH_VERSION_STAMP = Object.freeze({
  tradeSchemaVersion: LONG_TRADE_EXPORT_VERSION,
  entrySnapshotSchemaVersion: LONG_ENTRY_RESEARCH_SCHEMA_VERSION,
  scoreRegistryVersion: LONG_SCORE_REGISTRY_VERSION,
  filterRegistryVersion: LONG_FILTER_REGISTRY_VERSION,
  labelRegistryVersion: LONG_LABEL_REGISTRY_VERSION,
  comboRegistrySchemaVersion: LONG_COMBO_REGISTRY_SCHEMA_VERSION,
  antiComboRegistryVersion: LONG_ANTI_COMBO_REGISTRY_VERSION,
  winningSetupRegistryVersion: LONG_WINNING_SETUP_REGISTRY_VERSION,
  marketContextVersion: LONG_MARKET_CONTEXT_VERSION,
  exitSystemVersion: LONG_EXIT_SYSTEM_VERSION,
  feeModelVersion: LONG_FEE_MODEL_VERSION,
  pnlModelVersion: LONG_PNL_MODEL_VERSION,
  tickDirectionVersion: LONG_TICK_DIRECTION_VERSION,
});

export function makeLongResearchVersionStamp() {
  return { ...LONG_RESEARCH_VERSION_STAMP };
}
