export const TICK_DATA_QUALITY = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  INSUFFICIENT: "INSUFFICIENT",
  STALE: "STALE",
});

export const TICK_DIRECTION = Object.freeze({
  UP: "UP",
  DOWN: "DOWN",
  FLAT: "FLAT",
  MIXED: "MIXED",
  INSUFFICIENT: "INSUFFICIENT",
});

export const TICK_VERDICT = Object.freeze({
  STRONG_UP: "STRONG_UP",
  UP: "UP",
  NEUTRAL: "NEUTRAL",
  DOWN: "DOWN",
  STRONG_DOWN: "STRONG_DOWN",
  INSUFFICIENT: "INSUFFICIENT",
});

export const TICK_PATTERN = Object.freeze({
  UP_EXPANSION: "TICK_UP_EXPANSION",
  UP_PERSISTENT: "TICK_UP_PERSISTENT",
  UP_DECELERATION: "TICK_UP_DECELERATION",
  BULLISH_REVERSAL: "TICK_BULLISH_REVERSAL",
  DOWN_EXPANSION: "TICK_DOWN_EXPANSION",
  DOWN_PERSISTENT: "TICK_DOWN_PERSISTENT",
  DOWN_DECELERATION: "TICK_DOWN_DECELERATION",
  BEARISH_REVERSAL: "TICK_BEARISH_REVERSAL",
  HIGH_VOL_CHAOS: "TICK_HIGH_VOL_CHAOS",
  STALLED: "TICK_STALLED",
  MIXED: "TICK_MIXED",
  INSUFFICIENT: "TICK_INSUFFICIENT",
});

export const TICK_OUTCOME_RESULT = Object.freeze({
  CORRECT: "CORRECT",
  WRONG: "WRONG",
  NEUTRAL_TARGET: "NEUTRAL_TARGET",
  NEUTRAL_PREDICTION: "NEUTRAL_PREDICTION",
  CENSORED: "CENSORED",
  INSUFFICIENT_ENTRY_PREDICTION: "INSUFFICIENT_ENTRY_PREDICTION",
  MISSING_HORIZON_PRICE: "MISSING_HORIZON_PRICE",
});
