export const DIAGNOSTIC_ENTRY_POLICY_DECISION = {
  WOULD_ALLOW_FULL:   "WOULD_ALLOW_FULL",
  WOULD_ALLOW_STRICT: "WOULD_ALLOW_STRICT",
  WOULD_ALLOW_REDUCED: "WOULD_ALLOW_REDUCED",
  WOULD_SNIPER_ONLY:  "WOULD_SNIPER_ONLY",

  WOULD_BLOCK_LOW_QUALITY:          "WOULD_BLOCK_LOW_QUALITY",
  WOULD_BLOCK_LONG_AUDIT_DANGER:    "WOULD_BLOCK_LONG_AUDIT_DANGER",
  WOULD_BLOCK_MARKET_BREATH_DANGER: "WOULD_BLOCK_MARKET_BREATH_DANGER",
  WOULD_BLOCK_GREEN_DANGER:         "WOULD_BLOCK_GREEN_DANGER",
  WOULD_BLOCK_BULLISH_CVD:          "WOULD_BLOCK_BULLISH_CVD",
  WOULD_BLOCK_STALE_CONTEXT:        "WOULD_BLOCK_STALE_CONTEXT",
  WOULD_BLOCK_INVALID_TELEMETRY:    "WOULD_BLOCK_INVALID_TELEMETRY",

  WOULD_WARN_ONLY: "WOULD_WARN_ONLY",
};

export const DIAGNOSTIC_ENTRY_POLICY_ACTION = {
  LOG_WOULD_EXECUTE:              "LOG_WOULD_EXECUTE",
  LOG_WOULD_EXECUTE_REDUCED:      "LOG_WOULD_EXECUTE_REDUCED",
  LOG_WOULD_EXECUTE_SNIPER_ONLY:  "LOG_WOULD_EXECUTE_SNIPER_ONLY",
  LOG_WOULD_SKIP_ENTRY:           "LOG_WOULD_SKIP_ENTRY",
  LOG_WARNING_ONLY:               "LOG_WARNING_ONLY",
};
