// ─── LONG FILTER REGISTRY V2 ──────────────────────────────────────────────────
// Source of truth for all LongLAB research filters.
// The UI must render controls from this registry only.
// LOG_ONLY / RESEARCH_ONLY — no registry entry may affect execution.

import {
  LONG_FILTER_REGISTRY_VERSION,
  LONG_SCOPE,
  FILTER_TIMING,
  FIELD_TYPE,
  OPERATOR,
  BOOLEAN_OPERATORS,
  NUMERIC_OPERATORS,
  ENUM_OPERATORS,
  ARRAY_OPERATORS,
  FILTER_FAMILY,
  FILTER_STATUS,
} from "./longFilterConstants.js";
import { LONG_PF10_TIER } from "../scoring/longPostFee10/longPostFee10.constants.js";
import { LONG_RUNNER_TIER } from "../scoring/longCandidateRunner/longCandidateRunner.constants.js";

// ─── UNIVERSAL GATE ───────────────────────────────────────────────────────────

const UNIVERSAL_GATE_FILTERS = [
  {
    id: "LONG_PARENT_BUCKET",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Parent Bucket",
    description: "Top Gainer / Top Loser Long parent bucket captured at entry.",
    family: FILTER_FAMILY.SCOPE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longParentBucket",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [LONG_SCOPE.TOP_GAINER_LONGS, LONG_SCOPE.TOP_LOSER_LONGS],
  },
  {
    id: "LONG_GATE_PASS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Pass",
    description: "Universal Long Gate would pass at finalized entry telemetry.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateWouldPass",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LONG_GATE_FAIL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Fail",
    description: "Universal Long Gate would fail at finalized entry telemetry.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateWouldPass",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LONG_GATE_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Score",
    description: "Universal Long Gate score (0–100).",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [60, 75, 85, 90, 95],
  },
  {
    id: "LONG_GATE_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Tier",
    description: "Canonical Long Gate tier using the historical V1 thresholds.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["PREMIUM", "STRONG", "WATCH", "RESEARCH_REJECT", "INSUFFICIENT_DATA"],
    positiveValues: ["PREMIUM", "STRONG"],
    dangerValues: ["RESEARCH_REJECT"],
  },
  {
    id: "LONG_GATE_RESEARCH_BAND_V2",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Research Band V2",
    description: "Granular Gate research band with explicit 95/90/85/75/60 thresholds.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateResearchBandV2",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["GATE_ELITE_95", "GATE_PREMIUM_90", "GATE_PREMIUM_85", "GATE_STRONG_75", "GATE_WATCH_60", "GATE_RESEARCH_REJECT", "INSUFFICIENT_DATA"],
    positiveValues: ["GATE_ELITE_95", "GATE_PREMIUM_90", "GATE_PREMIUM_85", "GATE_STRONG_75"],
    dangerValues: ["GATE_RESEARCH_REJECT"],
  },
  {
    id: "LONG_GATE_AUDIT_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Audit Label",
    description: "Canonical audit label from the Long Gate evaluation.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateAuditLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "WOULD_PASS_LONG_GATE",
      "WOULD_FAIL_IMMEDIATE_RED_IMPULSE",
      "WOULD_FAIL_BTC_STRONG_DOWN_NO_GREEN",
      "WOULD_FAIL_CVD_BEAR_NO_GREEN",
      "WOULD_FAIL_NO_LONG_MICRO_MOMENTUM",
      "WOULD_FAIL_MULTIPLE_REASONS",
    ],
  },
  {
    id: "LONG_GATE_FAIL_REASONS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Gate Fail Reasons",
    description: "Array of specific reasons the Long Gate would fail.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longGateFailReasons",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HAS_LONG_MICRO_MOMENTUM",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Has Long Micro Momentum",
    description: "Entry has positive long micro-momentum confirmation.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "hasLongMicroMomentum",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HAS_RSI_ROLLOVER_UP",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Has RSI Rollover Up",
    description: "RSI is rolling over upward at entry.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "hasRsiRolloverUp",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HAS_GREEN_CONFIRMATION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Has Green Confirmation",
    description: "Entry has green impulse or green candle confirmation.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "hasGreenConfirmation",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HAS_RED_DANGER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Has Red Danger",
    description: "Entry has immediate red impulse danger signal.",
    family: FILTER_FAMILY.UNIVERSAL_GATE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "hasRedDanger",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── MICRO MOMENTUM ───────────────────────────────────────────────────────────

const MICRO_MOMENTUM_FILTERS = [
  {
    id: "LONG_MICRO_MOMENTUM_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Micro Momentum Label",
    description: "Native long micro-momentum classification at entry.",
    family: FILTER_FAMILY.MICRO_MOMENTUM,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longMicroMomentumLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "MICRO_GREEN_MULTI_CONFIRM",
      "MICRO_GREEN_IMPULSE",
      "MICRO_TICKS_UP",
      "MICRO_RSI_ROLLOVER_UP",
      "MICRO_RED_PRESSURE",
      "MICRO_NO_LONG_CONFIRMATION",
    ],
    positiveValues: [
      "MICRO_GREEN_MULTI_CONFIRM",
      "MICRO_GREEN_IMPULSE",
      "MICRO_TICKS_UP",
      "MICRO_RSI_ROLLOVER_UP",
    ],
    dangerValues: [
      "MICRO_RED_PRESSURE",
      "MICRO_NO_LONG_CONFIRMATION",
    ],
  },
  {
    id: "LONG_MICRO_UP_CONFIRMATION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Narrow Micro-Up Confirmation",
    description: "Actual upward microstructure: last-3 ticks up, immediate green impulse, or a green micro label. RSI-only rollover is excluded.",
    family: FILTER_FAMILY.MICRO_MOMENTUM,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longMicroUpConfirmation",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LONG_MICRO_UP_CONFIRMATION_REASONS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Micro-Up Confirmation Reasons",
    description: "Entry-time reasons supporting narrow micro-up confirmation.",
    family: FILTER_FAMILY.MICRO_MOMENTUM,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longMicroUpConfirmationReasons",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["LAST_3_TICKS_UP", "IMMEDIATE_GREEN_IMPULSE", "MICRO_GREEN_MULTI_CONFIRM", "MICRO_GREEN_IMPULSE", "MICRO_TICKS_UP"],
  },
  {
    id: "RSI_LONG_MOMENTUM_EXPANSION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "RSI Long Momentum Expansion",
    description: "RSI long momentum-expansion label present at finalized entry telemetry.",
    family: FILTER_FAMILY.MICRO_MOMENTUM,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "rsiLongMomentumExpansion",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "MACD_BULLISH_EXPANSION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "MACD Bullish Expansion",
    description: "Positive and expanding MACD histogram at entry.",
    family: FILTER_FAMILY.MICRO_MOMENTUM,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "macdBullishExpansion",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── GREEN / RED CONFIRMATION ─────────────────────────────────────────────────

const GREEN_RED_FILTERS = [
  {
    id: "IMMEDIATE_GREEN_IMPULSE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Immediate Green Impulse",
    description: "Price shows immediate green impulse at entry.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "immediateGreenImpulse",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "GREEN_IMPULSE_DETECTED",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Green Impulse Detected",
    description: "Green impulse detected at or near entry.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "greenImpulseDetected",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "IMMEDIATE_RED_IMPULSE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Immediate Red Impulse",
    description: "Immediate red candle impulse present at entry — long danger signal.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "immediateRedImpulse",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "RED_IMPULSE_DETECTED",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Red Impulse Detected",
    description: "Red impulse detected at or near entry.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "redImpulseDetected",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LAST_3_TICKS_DIRECTION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Last 3 Closed 1m Candles (Legacy Tick Alias)",
    description: "Direction derived from the colors of the last three closed 1-minute candles. This is not a genuine market-tick stream.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "last3TicksDirection",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["UP", "MIXED", "DOWN"],
    positiveValues: ["UP"],
    dangerValues: ["DOWN"],
  },
  {
    id: "CANDLE_COLOR_AT_ENTRY",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Candle Color at Entry",
    description: "Color of the current candle at entry time.",
    family: FILTER_FAMILY.GREEN_RED_CONFIRMATION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "candleColorAtEntry",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["GREEN", "RED", "DOJI", "UNKNOWN"],
  },
];

// ─── CVD / FLOW ───────────────────────────────────────────────────────────────

const CVD_FILTERS = [
  {
    id: "CVD_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "CVD Label",
    description: "Cumulative Volume Delta classification at entry.",
    family: FILTER_FAMILY.CVD_FLOW,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "entryCvdLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["BULL", "NEUT", "BEAR", "UNKNOWN"],
    positiveValues: ["BULL", "NEUT"],
    dangerValues: ["BEAR"],
    compoundPredicates: [
      { id: "CVD_BULL_OR_NEUT", label: "CVD Bull or Neut", values: ["BULL", "NEUT"] },
      { id: "CVD_NOT_BEAR", label: "CVD Not Bear", excluded: ["BEAR"] },
    ],
  },
  {
    id: "CVD_RATIO",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "CVD Ratio",
    description: "Numeric CVD ratio at entry.",
    family: FILTER_FAMILY.CVD_FLOW,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "cvdRatio",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── VWAP / STRUCTURE ─────────────────────────────────────────────────────────

const VWAP_STRUCTURE_FILTERS = [
  {
    id: "VWAP_LONG_CONTEXT_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "VWAP Long Context",
    description: "Native long VWAP context label at entry.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "vwapLongContextLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "ABOVE_VWAP_GREEN_CVD_BULL_SUPPORT",
      "ABOVE_VWAP_GREEN_SUPPORT",
      "ABOVE_VWAP_NO_RED_PRESSURE",
      "VWAP_RECLAIM_CONFIRMED",
      "VWAP_RECLAIM_ATTEMPT_WITH_BULL",
      "VWAP_RECLAIM_ATTEMPT",
      "VWAP_RETEST_HOLD",
      "BELOW_VWAP_WITH_RED_DANGER",
      "BELOW_VWAP_NO_RECLAIM_YET",
      "VWAP_RECLAIM_FAILURE",
      "VWAP_NEUTRAL",
    ],
  },
  {
    id: "PRICE_VS_VWAP_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Price vs VWAP",
    description: "Raw price position relative to VWAP.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "entryPriceVsVwapLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: ["ABOVE_VWAP", "AT_VWAP", "BELOW_VWAP"],
  },
  {
    id: "PRICE_VS_VWAP_PCT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Price vs VWAP %",
    description: "Price distance from VWAP as percentage.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "entryPriceVsVwapPct",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "FAILED_BREAKDOWN_1M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Failed Breakdown (1m)",
    description: "Failed breakdown pattern on 1-minute chart — bullish reversal signal.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "failedBreakdown1m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "FAILED_BREAKDOWN_3M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Failed Breakdown (3m)",
    description: "Failed breakdown pattern on 3-minute chart.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "failedBreakdown3m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HIGHER_LOW_1M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Higher Low (1m)",
    description: "Higher low pattern on 1-minute chart — continuation structure.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "higherLow1m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "HIGHER_LOW_3M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Higher Low (3m)",
    description: "Higher low pattern on 3-minute chart.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "higherLow3m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "BREAKOUT_RETEST_1M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Breakout Retest Hold (1m)",
    description: "Breakout retest hold on 1-minute chart — continuation signal.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "breakoutRetest1m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "BREAKOUT_RETEST_3M",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Breakout Retest Hold (3m)",
    description: "Breakout retest hold on 3-minute chart.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "breakoutRetest3m",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LOWER_WICK_PCT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Lower Wick %",
    description: "Lower wick size as percentage — absorption signal when large.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "lowerWickPct",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "MARKET_STRUCTURE_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Market Structure Label",
    description: "Market structure classification at entry.",
    family: FILTER_FAMILY.VWAP_STRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "marketStructureLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "FAILED_BREAKDOWN",
      "HIGHER_LOW",
      "BREAKOUT_RETEST_HOLD",
      "LOWER_WICK_ABSORPTION",
      "NEUTRAL",
      "BEARISH",
    ],
  },
];

// ─── ENERGY / EXECUTION QUALITY ───────────────────────────────────────────────

const ENERGY_FILTERS = [
  {
    id: "ATR_PCT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "ATR %",
    description: "Average True Range as percentage at entry. High ATR = active price movement.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "atrPct",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [0.2, 0.6, 1.0, 1.5],
  },
  {
    id: "ATR_BUCKET",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "ATR Bucket",
    description: "ATR categorized into standard energy buckets.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "atrBucket",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "SPREAD_PCT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Spread %",
    description: "Bid-ask spread as percentage. Lower = cleaner execution.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "spreadPct",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [0.02, 0.05],
    dangerThreshold: 0.05,
  },
  {
    id: "VOL_ACCEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Volume Acceleration",
    description: "Volume acceleration ratio at entry.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "volAccel",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "ENTRY_RANK",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Entry Rank",
    description: "Leaderboard rank at entry time.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "entryRank",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "CHANGE_24H",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "24h Change %",
    description: "24-hour price change percentage at entry.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "change24h",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "FUNDING_RATE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Funding Rate",
    description: "Funding rate at entry. Negative = bullish bias from squeeze potential.",
    family: FILTER_FAMILY.ENERGY_EXECUTION,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "fundingRate",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── MARKET CONTEXT ───────────────────────────────────────────────────────────

const MARKET_CONTEXT_FILTERS = [
  {
    id: "BTC_LONG_CONTEXT_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "BTC Long Context",
    description: "BTC market regime context for long entries.",
    family: FILTER_FAMILY.MARKET_CONTEXT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "btcLongContextLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "BTC_STRONG_UP_LONG_TAILWIND",
      "BTC_WEAK_UP_LONG_TAILWIND",
      "BTC_CHOP_LONG_SELECTIVE",
      "BTC_MIXED_LONG_CONDITIONAL",
      "BTC_WEAK_DOWN_LONG_HEADWIND",
      "BTC_STRONG_DOWN_LONG_REVERSAL_ONLY",
      "BTC_UNKNOWN",
    ],
    positiveValues: ["BTC_STRONG_UP_LONG_TAILWIND", "BTC_WEAK_UP_LONG_TAILWIND"],
    dangerValues: ["BTC_WEAK_DOWN_LONG_HEADWIND", "BTC_STRONG_DOWN_LONG_REVERSAL_ONLY"],
  },
  {
    id: "BTC_LONG_CONTEXT_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "BTC Long Context Score",
    description: "Numeric BTC long context score.",
    family: FILTER_FAMILY.MARKET_CONTEXT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "btcLongContextScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "BTC_REGIME",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "BTC Regime",
    description: "Raw BTC market regime classification.",
    family: FILTER_FAMILY.MARKET_CONTEXT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "btcRegime",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "MARKET_CONTEXT_STALE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Market Context Stale",
    description: "Market context data was stale at entry time.",
    family: FILTER_FAMILY.MARKET_CONTEXT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "marketContextStale",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
];

// ─── TOP LOSER REVERSAL ───────────────────────────────────────────────────────

const TOP_LOSER_FILTERS = [
  {
    id: "TOP_LOSER_THESIS_LANE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Long Thesis Lane",
    description: "Long-native thesis lane for Top Loser reversal research.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserLongThesisLane",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "TOP_LOSER_SCALP_REVERSAL_CANDIDATE",
      "TOP_LOSER_RUNNER_REVERSAL_CANDIDATE",
      "TOP_LOSER_BTC_TAILWIND_GREEN_REVERSAL",
      "TOP_LOSER_RED_FADE_SETUP",
      "TOP_LOSER_LONG_REVERSAL_WATCH",
      "TOP_LOSER_NO_LONG_MOMENTUM_YET",
      "TOP_LOSER_BTC_HEADWIND_REVERSAL_RISK",
    ],
    positiveValues: ["TOP_LOSER_SCALP_REVERSAL_CANDIDATE", "TOP_LOSER_RUNNER_REVERSAL_CANDIDATE", "TOP_LOSER_BTC_TAILWIND_GREEN_REVERSAL"],
    dangerValues: ["TOP_LOSER_NO_LONG_MOMENTUM_YET", "TOP_LOSER_BTC_HEADWIND_REVERSAL_RISK"],
  },
  {
    id: "TOP_LOSER_SUB_BUCKET",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Sub-Bucket",
    description: "Native long sub-bucket for Top Loser entries.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserLongSubBucket",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "TOP_LOSER_FAILED_BREAKDOWN_LONG",
      "TOP_LOSER_SELLER_EXHAUSTION_LONG",
      "TOP_LOSER_FIRST_GREEN_CANDLE_LONG",
      "TOP_LOSER_VWAP_RECLAIM_LONG",
      "TOP_LOSER_VWAP_RETEST_HOLD_LONG",
      "TOP_LOSER_GREEN_MULTI_CONFIRM_LONG",
      "TOP_LOSER_SHORT_SQUEEZE_CANDIDATE",
      "TOP_LOSER_RELIEF_BOUNCE_LONG",
      "TOP_LOSER_DUMP_EXHAUSTION_LONG",
      "TOP_LOSER_UNCLASSIFIED_LONG",
      "TOP_LOSER_RED_REACCELERATION_DANGER",
      "TOP_LOSER_CVD_BEAR_DANGER",
      "TOP_LOSER_DUMP_STILL_HOT",
      "TOP_LOSER_FALLING_KNIFE_DANGER",
      "TOP_LOSER_THIN_BOOK_DANGER",
    ],
    positiveValues: [
      "TOP_LOSER_FAILED_BREAKDOWN_LONG",
      "TOP_LOSER_SELLER_EXHAUSTION_LONG",
      "TOP_LOSER_FIRST_GREEN_CANDLE_LONG",
      "TOP_LOSER_VWAP_RECLAIM_LONG",
      "TOP_LOSER_VWAP_RETEST_HOLD_LONG",
      "TOP_LOSER_GREEN_MULTI_CONFIRM_LONG",
      "TOP_LOSER_SHORT_SQUEEZE_CANDIDATE",
      "TOP_LOSER_RELIEF_BOUNCE_LONG",
      "TOP_LOSER_DUMP_EXHAUSTION_LONG",
    ],
    dangerValues: [
      "TOP_LOSER_RED_REACCELERATION_DANGER",
      "TOP_LOSER_CVD_BEAR_DANGER",
      "TOP_LOSER_DUMP_STILL_HOT",
      "TOP_LOSER_FALLING_KNIFE_DANGER",
      "TOP_LOSER_THIN_BOOK_DANGER",
    ],
  },
  {
    id: "TOP_LOSER_REVERSAL_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Score",
    description: "Reversal audit score for Top Loser entries (0–100).",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [50, 70],
  },
  {
    id: "TOP_LOSER_REVERSAL_WOULD_PASS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Would Pass",
    description: "Top Loser reversal audit would pass (score >= 50).",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalWouldPass",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "TOP_LOSER_REVERSAL_THESIS_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Thesis Label",
    description: "Reversal thesis confidence label.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalThesisLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "REVERSAL_CONFIRMED",
      "REVERSAL_LIKELY",
      "REVERSAL_POSSIBLE",
      "REVERSAL_UNLIKELY",
    ],
    positiveValues: ["REVERSAL_CONFIRMED", "REVERSAL_LIKELY"],
    dangerValues: ["REVERSAL_UNLIKELY"],
  },
  {
    id: "TOP_LOSER_REVERSAL_REASONS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Reasons",
    description: "Confirmed reversal signals for the entry.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalReasons",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "FAILED_BREAKDOWN", "GREEN_IMPULSE", "LOWER_WICK_ABSORPTION",
      "HIGHER_LOW_CONFIRMED", "CVD_BULL", "VWAP_RECLAIM",
      "LAST3_TICKS_UP", "BTC_TAILWIND", "NEGATIVE_FUNDING_SQUEEZE", "ATR_ACTIVE",
    ],
  },
  {
    id: "TOP_LOSER_REVERSAL_WARNINGS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Warnings",
    description: "Danger signals for the Top Loser entry.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalWarnings",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "IMMEDIATE_RED_IMPULSE", "CVD_BEAR", "BTC_HEADWIND_NO_GREEN",
    ],
  },
  {
    id: "TOP_LOSER_REVERSAL_CONFIRM_COUNT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Loser Reversal Confirm Count",
    description: "Number of reversal confirmation signals present.",
    family: FILTER_FAMILY.TOP_LOSER_REVERSAL,
    scope: LONG_SCOPE.TOP_LOSER_LONGS,
    field: "topLoserReversalConfirmCount",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [2, 3],
  },
];

// ─── TOP GAINER CONTINUATION ──────────────────────────────────────────────────

const TOP_GAINER_FILTERS = [
  {
    id: "TOP_GAINER_SUB_BUCKET",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Sub-Bucket",
    description: "Native long sub-bucket for Top Gainer entries.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerLongSubBucket",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "TOP_GAINER_VWAP_SUPPORT_LONG",
      "TOP_GAINER_HIGHER_LOW_LONG",
      "TOP_GAINER_BREAKOUT_RETEST_LONG",
      "TOP_GAINER_GREEN_REACCELERATION_LONG",
      "TOP_GAINER_CONTINUATION_LONG",
      "TOP_GAINER_PULLBACK_HOLD_LONG",
      "TOP_GAINER_TREND_RESUMPTION_LONG",
      "TOP_GAINER_MICRO_MULTI_CONFIRM_LONG",
      "TOP_GAINER_UNCLASSIFIED_LONG",
      "TOP_GAINER_OVEREXTENDED_NO_PULLBACK",
      "TOP_GAINER_FAILED_BREAKOUT_DANGER",
      "TOP_GAINER_VWAP_LOSS_DANGER",
      "TOP_GAINER_CVD_DIVERGENCE_DANGER",
      "TOP_GAINER_LONG_CROWDING_DANGER",
      "TOP_GAINER_PUMP_STALL_DANGER",
      "TOP_GAINER_BLOWOFF_DANGER",
    ],
    positiveValues: [
      "TOP_GAINER_VWAP_SUPPORT_LONG",
      "TOP_GAINER_HIGHER_LOW_LONG",
      "TOP_GAINER_BREAKOUT_RETEST_LONG",
      "TOP_GAINER_GREEN_REACCELERATION_LONG",
      "TOP_GAINER_CONTINUATION_LONG",
      "TOP_GAINER_PULLBACK_HOLD_LONG",
      "TOP_GAINER_TREND_RESUMPTION_LONG",
      "TOP_GAINER_MICRO_MULTI_CONFIRM_LONG",
    ],
    dangerValues: [
      "TOP_GAINER_OVEREXTENDED_NO_PULLBACK",
      "TOP_GAINER_FAILED_BREAKOUT_DANGER",
      "TOP_GAINER_VWAP_LOSS_DANGER",
      "TOP_GAINER_CVD_DIVERGENCE_DANGER",
      "TOP_GAINER_LONG_CROWDING_DANGER",
      "TOP_GAINER_PUMP_STALL_DANGER",
      "TOP_GAINER_BLOWOFF_DANGER",
    ],
  },
  {
    id: "TOP_GAINER_CONTINUATION_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Score",
    description: "Continuation audit score for Top Gainer entries (0–100).",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [50, 70],
  },
  {
    id: "TOP_GAINER_BLOWOFF_RISK_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Blowoff Risk Score",
    description: "Blowoff risk score for Top Gainer entries. Higher = more danger.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerBlowoffRiskScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [20, 30],
  },
  {
    id: "TOP_GAINER_CONTINUATION_WOULD_PASS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Would Pass",
    description: "Top Gainer continuation audit would pass (score >= 50).",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationWouldPass",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "TOP_GAINER_CONTINUATION_THESIS_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Thesis Label",
    description: "Continuation thesis confidence label.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationThesisLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "CONTINUATION_CONFIRMED",
      "CONTINUATION_LIKELY",
      "CONTINUATION_POSSIBLE",
      "CONTINUATION_UNLIKELY",
    ],
    positiveValues: ["CONTINUATION_CONFIRMED", "CONTINUATION_LIKELY"],
    dangerValues: ["CONTINUATION_UNLIKELY"],
  },
  {
    id: "TOP_GAINER_CONTINUATION_DANGER_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Danger Label",
    description: "Specific danger classification for the gainer entry.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationDangerLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "TOP_GAINER_CONTINUATION_CLEAR",
      "TOP_GAINER_FAILED_BREAKOUT_DANGER",
      "TOP_GAINER_VWAP_LOSS_DANGER",
      "TOP_GAINER_BLOWOFF_DANGER",
    ],
  },
  {
    id: "TOP_GAINER_CONTINUATION_REASONS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Reasons",
    description: "Confirmed continuation signals for the gainer entry.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationReasons",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "ABOVE_VWAP_SUPPORT", "HIGHER_LOW", "BREAKOUT_RETEST_HOLD",
      "CVD_BULL", "GREEN_REACCELERATION", "MACD_POSITIVE_EXPANSION",
      "RSI_STRONG_RISING", "PUMP_STILL_ACTIVE",
    ],
  },
  {
    id: "TOP_GAINER_CONTINUATION_WARNINGS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Top Gainer Continuation Warnings",
    description: "Danger signals for the Top Gainer entry.",
    family: FILTER_FAMILY.TOP_GAINER_CONTINUATION,
    scope: LONG_SCOPE.TOP_GAINER_LONGS,
    field: "topGainerContinuationWarnings",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "UPPER_WICK_REJECTION", "IMMEDIATE_RED_IMPULSE", "CVD_BEAR_DIVERGENCE",
      "BELOW_VWAP", "POSITIVE_FUNDING_CROWDING", "SPREAD_ABOVE_0_05",
    ],
  },
];

// ─── LONG AES ─────────────────────────────────────────────────────────────────

const LONG_AES_FILTERS = [
  {
    id: "LONG_AES_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long AES Score",
    description: "Native Long Absolute Entry Score (0–100).",
    family: FILTER_FAMILY.LONG_AES,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longAesScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [40, 55, 70, 80, 90],
  },
  {
    id: "LONG_AES_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long AES Tier",
    description: "Native Long AES tier label.",
    family: FILTER_FAMILY.LONG_AES,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longAesTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LONG_AES_ELIGIBILITY",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long AES Eligibility",
    description: "Long AES eligibility classification.",
    family: FILTER_FAMILY.LONG_AES,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longAesEligibility",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── LONG BEST DNA ────────────────────────────────────────────────────────────

const LONG_BEST_DNA_FILTERS = [
  {
    id: "BEST_DNA_LONG_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Best DNA Long Score",
    description: "Native Long Best DNA score (0–100).",
    family: FILTER_FAMILY.LONG_BEST_DNA,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "bestDnaLongScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [55, 70, 85, 95],
  },
  {
    id: "BEST_DNA_LONG_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Best DNA Long Tier",
    description: "Native Long Best DNA tier label.",
    family: FILTER_FAMILY.LONG_BEST_DNA,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "bestDnaLongTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "BEST_DNA_LONG_ELITE",
      "BEST_DNA_LONG_SNIPER",
      "BEST_DNA_LONG_HIGH",
      "BEST_DNA_LONG_CANDIDATE",
      "BEST_DNA_LONG_WATCH",
      "BEST_DNA_LONG_LOW",
    ],
  },
  {
    id: "BEST_DNA_LONG_PRIMARY_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Best DNA Long Primary Label",
    description: "Primary Best DNA Long label for the entry.",
    family: FILTER_FAMILY.LONG_BEST_DNA,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "bestDnaLongPrimaryLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "BEST_DNA_LONG_POSITIVE_GENES",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Best DNA Long Positive Genes",
    description: "Array of positive gene signals in the Best DNA Long audit.",
    family: FILTER_FAMILY.LONG_BEST_DNA,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "bestDnaLongPositiveGenes",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "BEST_DNA_LONG_PENALTY_GENES",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Best DNA Long Penalty Genes",
    description: "Array of penalty gene signals in the Best DNA Long audit.",
    family: FILTER_FAMILY.LONG_BEST_DNA,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "bestDnaLongPenaltyGenes",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── LONG POST-FEE-10 ─────────────────────────────────────────────────────────

const LONG_POST_FEE_10_FILTERS = [
  {
    id: "LONG_POST_FEE_10_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Post-Fee-10 Entry Score",
    description: "Native Long Post-Fee-10 entry potential score (0–100).",
    family: FILTER_FAMILY.LONG_POST_FEE_10,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longPostFee10EntryScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [50, 65, 85, 95],
  },
  {
    id: "LONG_POST_FEE_10_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Post-Fee-10 Entry Tier",
    description: "Native Long Post-Fee-10 entry tier label.",
    family: FILTER_FAMILY.LONG_POST_FEE_10,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longPostFee10EntryTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: Object.values(LONG_PF10_TIER),
  },
  {
    id: "LONG_POST_FEE_10_POSITIVE_GENES",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Post-Fee-10 Positive Genes",
    description: "Array of positive gene signals in the Post-Fee-10 audit.",
    family: FILTER_FAMILY.LONG_POST_FEE_10,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longPostFee10PositiveGenes",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "RUNNER_CAPTURE_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Runner Capture Potential Score",
    description: "LIVE runner capture potential score (0–100). Exit-management study only — NOT an entry signal.",
    family: FILTER_FAMILY.EXIT_MANAGEMENT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "runnerCapturePotentialScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.POST_ENTRY_LIVE,
    sourceTiming: "LIVE",
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
    presets: [50, 65, 80, 90],
  },
  {
    id: "RUNNER_CAPTURE_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Runner Capture Potential Tier",
    description: "LIVE runner capture potential tier. Exit-management study only — NOT an entry signal.",
    family: FILTER_FAMILY.EXIT_MANAGEMENT,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "runnerCapturePotentialTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.POST_ENTRY_LIVE,
    sourceTiming: "LIVE",
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
    enumValues: [
      "RUNNER_POTENTIAL_ELITE",
      "RUNNER_POTENTIAL_SNIPER",
      "RUNNER_POTENTIAL_HIGH",
      "RUNNER_POTENTIAL_WATCH",
      "RUNNER_POTENTIAL_LOW",
    ],
  },
];

// ─── SNIPER LONG ──────────────────────────────────────────────────────────────

const SNIPER_LONG_FILTERS = [
  {
    id: "SNIPER_LONG_WOULD_PASS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Sniper Long Would Pass",
    description: "Sniper Long gate would pass (log-only).",
    family: FILTER_FAMILY.SNIPER_LONG,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "sniperLongWouldPass",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "SNIPER_LONG_TIER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Sniper Long Tier",
    description: "Sniper Long tier classification.",
    family: FILTER_FAMILY.SNIPER_LONG,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "sniperLongTier",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "SNIPER_LONG_SCORE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Sniper Long Score",
    description: "Sniper Long score (0–100).",
    family: FILTER_FAMILY.SNIPER_LONG,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "sniperLongScore",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "SNIPER_LONG_REASONS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Sniper Long Reasons",
    description: "Signals that caused Sniper Long to pass.",
    family: FILTER_FAMILY.SNIPER_LONG,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "sniperLongReasons",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── POSITIVE COMBOS ──────────────────────────────────────────────────────────

const POSITIVE_COMBO_FILTERS = [
  {
    id: "LONG_COMBOS_POSITIVE_MATCHED",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Positive Long Combos Matched",
    description: "Array of positive long combo IDs that matched for this entry.",
    family: FILTER_FAMILY.POSITIVE_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCombosPositiveMatched",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "LONG_UNIVERSAL_CORE_V1",
      "FIRST_GREEN_DUMP_EXHAUSTION_LONG_V1",
      "FAILED_BREAKDOWN_VWAP_RECLAIM_LONG_V1",
      "NEGATIVE_FUNDING_SQUEEZE_LONG_V1",
      "TOP_GAINER_HIGHER_LOW_CONTINUATION_LONG_V1",
      "BREAKOUT_RETEST_CONTINUATION_LONG_V1",
      "LONG_UNIVERSAL_CORE_MICRO_UP_V1",
      "LONG_GATE_RSI_MACD_EXPANSION_V1",
      "LONG_PREMIUM_PF10_RUNNER_V1",
      "LONG_GATE_STRONG_MICRO_UP_CLEAN_V1",
      "LONG_BULL_CONFIRMED_VWAP_RECLAIM_V1",
      "LONG_GAINER_GREEN_REACCELERATION_V1",
      "LONG_LOSER_SCALP_REVERSAL_CONFIRMED_V1",
    ],
  },
  {
    id: "LONG_COMBOS_POSITIVE_COUNT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Positive Long Combo Count",
    description: "Number of positive long combos matched.",
    family: FILTER_FAMILY.POSITIVE_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCombosPositiveCount",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [1, 2, 3],
  },
];

// ─── ANTI-COMBOS ──────────────────────────────────────────────────────────────

const ANTI_COMBO_FILTERS = [
  {
    id: "LONG_COMBOS_ANTI_MATCHED",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Anti-Long Combos Matched",
    description: "Array of anti-long combo IDs that matched — danger signals.",
    family: FILTER_FAMILY.ANTI_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCombosAntiMatched",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "LONG_FALLING_KNIFE_ANTI_V1",
      "LONG_RED_CVD_BEAR_ANTI_V1",
    ],
  },
  {
    id: "LONG_COMBOS_ANTI_COUNT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Anti-Long Combo Count",
    description: "Number of anti-long combos matched. Zero is best.",
    family: FILTER_FAMILY.ANTI_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCombosAntiCount",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── CURATED WINNING SETUP MATCHES ───────────────────────────────────────────

const WINNING_SETUP_FILTERS = [
  {
    id: "ACTIVE_WINNING_SETUP_IDS",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Matched Winning Setup IDs",
    description: "Curated entry-time Winning Setup definitions matched by this trade.",
    family: FILTER_FAMILY.POSITIVE_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "activeWinningSetupIds",
    fieldType: FIELD_TYPE.ARRAY,
    operators: ARRAY_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
  {
    id: "LONG_WINNING_SETUP_CATALOG_VERSION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Winning Setup Catalog Version",
    description: "Version of the curated Long Winning Setup catalog used at entry.",
    family: FILTER_FAMILY.POSITIVE_COMBOS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longWinningSetupCatalogVersion",
    fieldType: FIELD_TYPE.STRING,
    operators: [OPERATOR.EQ, OPERATOR.IN, OPERATOR.IS_KNOWN, OPERATOR.IS_UNKNOWN],
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
  },
];

// ─── SHADOW POLICY (log-only diagnostics) ────────────────────────────────────

const SHADOW_POLICY_FILTERS = [
  {
    id: "LONG_AUDIT_DANGER_LABEL",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Audit Danger Label",
    description: "Log-only LONG entry danger audit classification (not execution).",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longAuditDangerLabel",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "LONG_DANGER_DATA_INCOMPLETE",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Danger: Data Incomplete",
    description: "Research snapshot flagged as having incomplete entry data (log-only).",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longDangerDataIncomplete",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEGATIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "LONG_DANGER_DATA_CONFLICTED",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Long Danger: Data Conflicted",
    description: "Research snapshot flagged as having conflicting signal data (log-only).",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longDangerDataConflicted",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEGATIVE",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "LONG_SHADOW_DECISION",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Shadow Decision",
    description: "Unified research shadow verdict (log-only diagnostic).",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longShadowDecision",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: true,
    enumValues: [
      "WOULD_ALLOW_PREMIUM",
      "WOULD_ALLOW",
      "WOULD_REDUCE",
      "WOULD_BLOCK",
      "WOULD_HARD_BLOCK",
      "UNKNOWN",
    ],
  },
];

// ─── OUTCOME FORENSICS (post-entry / exit fields) ─────────────────────────────

const OUTCOME_FORENSICS_FILTERS = [
  {
    id: "CLOSE_REASON",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Close Reason",
    description: "How the trade was closed.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "closeReason",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.EXIT_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
    enumValues: ["PROFIT_LOCK", "TRAIL", "SL", "TIMEOUT", "RUN_STOP", "APP_SHUTDOWN", "EMERGENCY_EXIT", "MANUAL_CLOSE", "FINALIZATION_FAILED"],
  },
  {
    id: "PROFIT_LOCK_EXIT_BELOW_FLOOR",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Profit Lock Exit Below Floor",
    description: "Outcome diagnostic: PROFIT_LOCK closed below its recorded floor.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "profitLockExitBelowFloor",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.EXIT_FINAL,
    polarity: "DANGER",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_POST_FEE_10_PLUS_WINNER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Post-Fee 10%+ Winner",
    description: "Trade achieved 10%+ net after fees.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isPostFee10PlusWinner",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_RUN_BEST_1_NORM",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Run Best 1 (Normalized)",
    description: "Trade is the top normalized winner of its run.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isRunBest1Norm",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_RUN_BEST_3_NORM",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Run Best 3 (Normalized)",
    description: "Trade is in the top 3 normalized winners of its run.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isRunBest3Norm",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_NORM_2_PLUS_WINNER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Norm 2%+ Winner",
    description: "Trade achieved 2%+ fee-adjusted normalized PnL.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isNorm2PlusWinner",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_NORM_3_PLUS_WINNER",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Norm 3%+ Winner",
    description: "Trade achieved 3%+ fee-adjusted normalized PnL.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isNorm3PlusWinner",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "IS_FINAL_OUTCOME",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Is Final Outcome",
    description: "Trade has a final realized outcome (not ACTIVE). Set by lifecycle normalization.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isFinalOutcome",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.EXIT_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
  },
  {
    id: "TIME_EXIT_ANY",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Time Exit (Any)",
    description: "Trade exited by its hold deadline (TIMEOUT). RUN_STOP and APP_SHUTDOWN are separate session lifecycle causes.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "isTimeExit",
    fieldType: FIELD_TYPE.BOOLEAN,
    operators: BOOLEAN_OPERATORS,
    timing: FILTER_TIMING.EXIT_FINAL,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive: false,
  },
];

// ─── CANDIDATE RUNNER FILTERS ────────────────────────────────────────────────

const CANDIDATE_RUNNER_FILTERS = [
  {
    id: "LONG_CANDIDATE_RUNNER_SCORE_AT_ENTRY",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Candidate Runner Score (Entry)",
    description: "Long Candidate Runner score computed at entry (0–100).",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCandidateRunnerScoreAtEntry",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    presets: [50, 65, 80, 90],
  },  {
    id: "LONG_CANDIDATE_RUNNER_TIER_AT_ENTRY",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Candidate Runner Tier (Entry)",
    description: "Canonical Long Candidate Runner tier computed at entry.",
    family: FILTER_FAMILY.SHADOW_POLICY,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "longCandidateRunnerTierAtEntry",
    fieldType: FIELD_TYPE.ENUM,
    operators: ENUM_OPERATORS,
    timing: FILTER_TIMING.ENTRY_FINAL,
    polarity: "POSITIVE",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: true,
    enumValues: Object.values(LONG_RUNNER_TIER),
  },
];

// ─── FEE-ADJUSTED OUTCOME FILTERS ─────────────────────────────────────────────

const FEE_ADJUSTED_OUTCOME_FILTERS = [
  {
    id: "FEE_ADJUSTED_NORM_PNL_PCT",
    version: LONG_FILTER_REGISTRY_VERSION,
    label: "Fee-Adjusted Normalized PnL %",
    description: "Fee-adjusted normalized PnL as a percentage. Canonical outcome metric.",
    family: FILTER_FAMILY.OUTCOME_FORENSICS,
    scope: LONG_SCOPE.ALL_LONGS,
    field: "feeAdjustedNormPnlPct",
    fieldType: FIELD_TYPE.NUMERIC,
    operators: NUMERIC_OPERATORS,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    polarity: "NEUTRAL",
    status: FILTER_STATUS.ACTIVE,
    executionSafe: false,
    entryPredictive: false,
    presets: [0, 2, 5, 10],
  },
];

// ─── GENUINE TICK MICROSTRUCTURE (LOG ONLY) ───────────────────────────────

function tickFilter({
  id,
  label,
  field,
  fieldType = FIELD_TYPE.NUMERIC,
  timing = FILTER_TIMING.ENTRY_FINAL,
  entryPredictive = true,
  enumValues,
  polarity = "NEUTRAL",
}) {
  return {
    id,
    version: LONG_FILTER_REGISTRY_VERSION,
    label,
    description: timing === FILTER_TIMING.OUTCOME_ONLY
      ? `${label} from the fixed-horizon tick prediction audit. Outcome-only research field.`
      : `${label} from the entry-frozen Binance Futures tick observatory.`,
    family: FILTER_FAMILY.TICK_MICROSTRUCTURE,
    scope: LONG_SCOPE.ALL_LONGS,
    field,
    fieldType,
    operators: fieldType === FIELD_TYPE.ENUM
      ? ENUM_OPERATORS
      : fieldType === FIELD_TYPE.ARRAY
        ? ARRAY_OPERATORS
        : NUMERIC_OPERATORS,
    timing,
    polarity,
    status: FILTER_STATUS.RESEARCH,
    executionSafe: false,
    entryPredictive,
    ...(enumValues ? { enumValues } : {}),
  };
}

const TICK_MICROSTRUCTURE_FILTERS = [
  tickFilter({ id: "ENTRY_TICK_DATA_QUALITY", label: "Entry Tick Data Quality", field: "entryTickDataQuality", fieldType: FIELD_TYPE.ENUM, enumValues: ["COMPLETE", "PARTIAL", "INSUFFICIENT", "STALE"] }),
  tickFilter({ id: "MARKET_TICK_CANONICAL_SOURCE", label: "Market Tick Canonical Source", field: "entryTickCanonicalSource", fieldType: FIELD_TYPE.ENUM, enumValues: ["AGG_TRADE", "BOOK_TICKER_MID", "INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_DIRECTION_VERDICT", label: "Market Tick Direction Verdict", field: "marketTickDirectionVerdict", fieldType: FIELD_TYPE.ENUM, enumValues: ["STRONG_UP", "UP", "NEUTRAL", "DOWN", "STRONG_DOWN", "INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_PRIMARY_PATTERN", label: "Market Tick Primary Pattern", field: "marketTickPrimaryPattern", fieldType: FIELD_TYPE.ENUM, enumValues: ["TICK_UP_EXPANSION", "TICK_UP_PERSISTENT", "TICK_UP_DECELERATION", "TICK_BULLISH_REVERSAL", "TICK_DOWN_EXPANSION", "TICK_DOWN_PERSISTENT", "TICK_DOWN_DECELERATION", "TICK_BEARISH_REVERSAL", "TICK_HIGH_VOL_CHAOS", "TICK_STALLED", "TICK_MIXED", "TICK_INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_DIRECTION_3S", label: "Market Tick Direction 3s", field: "marketTickDirection3s", fieldType: FIELD_TYPE.ENUM, enumValues: ["UP", "DOWN", "FLAT", "MIXED", "INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_DIRECTION_10S", label: "Market Tick Direction 10s", field: "marketTickDirection10s", fieldType: FIELD_TYPE.ENUM, enumValues: ["UP", "DOWN", "FLAT", "MIXED", "INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_BIAS_SCORE", label: "Market Tick Directional Bias", field: "marketTickDirectionalBiasScore" }),
  tickFilter({ id: "MARKET_TICK_CONFIDENCE_SCORE", label: "Market Tick Direction Confidence", field: "marketTickDirectionConfidenceScore" }),
  tickFilter({ id: "MARKET_TICK_NET_MOVE_BPS_3S", label: "Market Tick Net Move 3s", field: "marketTickNetMoveBps3s" }),
  tickFilter({ id: "MARKET_TICK_NET_MOVE_BPS_10S", label: "Market Tick Net Move 10s", field: "marketTickNetMoveBps10s" }),
  tickFilter({ id: "MARKET_TICK_EFFICIENCY_3S", label: "Market Tick Efficiency 3s", field: "marketTickEfficiency3s" }),
  tickFilter({ id: "MARKET_TICK_EFFICIENCY_10S", label: "Market Tick Efficiency 10s", field: "marketTickEfficiency10s" }),
  tickFilter({ id: "MARKET_TICK_VELOCITY_3S", label: "Market Tick Velocity 3s", field: "marketTickVelocityBpsPerSec3s" }),
  tickFilter({ id: "MARKET_TICK_ACCELERATION_3S", label: "Market Tick Acceleration 3s", field: "marketTickAccelerationBpsPerSec2_3s" }),
  tickFilter({ id: "MARKET_TICK_CURRENT_UP_STREAK", label: "Market Tick Current Up Streak", field: "marketTickCurrentUpStreak" }),
  tickFilter({ id: "MARKET_TICK_CURRENT_DOWN_STREAK", label: "Market Tick Current Down Streak", field: "marketTickCurrentDownStreak" }),
  tickFilter({ id: "MARKET_TICK_REVERSAL_COUNT_10", label: "Market Tick Reversal Count 10", field: "marketTickReversalCount10" }),
  tickFilter({ id: "MARKET_TICK_AGGRESSOR_FLOW_3S", label: "Market Tick Aggressor Flow 3s", field: "marketTickAggressorFlowLabel3s", fieldType: FIELD_TYPE.ENUM, enumValues: ["STRONG_BUY", "BUY", "NEUTRAL", "SELL", "STRONG_SELL", "INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_AGGRESSOR_VOLUME_IMBALANCE_3S", label: "Aggressor Volume Imbalance 3s", field: "marketTickAggressorVolumeImbalance3s" }),
  tickFilter({ id: "MARKET_TICK_BOOK_IMBALANCE_3S", label: "Book Imbalance Mean 3s", field: "marketTickBookImbalanceMean3s" }),
  tickFilter({ id: "MARKET_TICK_TRADE_BOOK_AGREEMENT_3S", label: "Trade / Book Agreement 3s", field: "marketTickTradeBookAgreement3s", fieldType: FIELD_TYPE.ENUM, enumValues: ["AGREE_UP", "AGREE_DOWN", "DISAGREE", "ONE_SOURCE_ONLY", "BOTH_INSUFFICIENT"] }),
  tickFilter({ id: "MARKET_TICK_EVIDENCE_AGREEMENT_LABEL", label: "Tick / Indicator Evidence Agreement", field: "marketTickEvidenceAgreementLabel", fieldType: FIELD_TYPE.ENUM, enumValues: ["STRONG_AGREEMENT", "AGREEMENT", "MIXED", "CONFLICT"] }),
  tickFilter({ id: "HIGH_ATR_TICK_CONTEXT_LABEL", label: "High ATR Tick Context", field: "highAtrTickContextLabel", fieldType: FIELD_TYPE.ENUM, enumValues: ["HIGH_ATR_TICK_UP_EXPANSION", "HIGH_ATR_TICK_BULLISH_REVERSAL", "HIGH_ATR_TICK_UP_DECELERATION", "HIGH_ATR_TICK_DOWN_EXPANSION", "HIGH_ATR_TICK_BEARISH_REVERSAL", "HIGH_ATR_TICK_CHAOS", "HIGH_ATR_TICK_STALLED", "ATR_NOT_ACTIVE", "TICK_DIRECTION_UNKNOWN"] }),
  tickFilter({ id: "HIGH_ATR_DIRECTIONAL_OPPORTUNITY_SCORE", label: "High ATR Directional Opportunity", field: "highAtrDirectionalOpportunityScore" }),
  tickFilter({ id: "LONG_TICK_RESEARCH_HYPOTHESES_MATCHED", label: "Long Tick Research Hypotheses", field: "longTickResearchHypothesesMatched", fieldType: FIELD_TYPE.ARRAY }),
  tickFilter({ id: "LONG_TICK_RISK_PATTERNS_MATCHED", label: "Long Tick Risk Patterns", field: "longTickRiskPatternsMatched", fieldType: FIELD_TYPE.ARRAY }),
];

const TICK_OUTCOME_FILTERS = ["1s", "3s", "5s", "10s", "30s", "60s"].flatMap(horizon => [
  tickFilter({
    id: `MARKET_TICK_PREDICTION_RESULT_${horizon.toUpperCase()}`,
    label: `Market Tick Prediction Result ${horizon}`,
    field: `marketTickPredictionResult${horizon}`,
    fieldType: FIELD_TYPE.ENUM,
    enumValues: ["CORRECT", "WRONG", "NEUTRAL_TARGET", "NEUTRAL_PREDICTION", "CENSORED", "INSUFFICIENT_ENTRY_PREDICTION", "MISSING_HORIZON_PRICE"],
    timing: FILTER_TIMING.OUTCOME_ONLY,
    entryPredictive: false,
  }),
  tickFilter({
    id: `MARKET_TICK_FORWARD_MOVE_BPS_${horizon.toUpperCase()}`,
    label: `Market Tick Forward Move ${horizon}`,
    field: `marketTickForwardMoveBps${horizon}`,
    timing: FILTER_TIMING.OUTCOME_ONLY,
    entryPredictive: false,
  }),
]);

// ─── COMBINED REGISTRY ────────────────────────────────────────────────────────

export const LONG_FILTER_REGISTRY = [
  ...UNIVERSAL_GATE_FILTERS,
  ...MICRO_MOMENTUM_FILTERS,
  ...GREEN_RED_FILTERS,
  ...CVD_FILTERS,
  ...VWAP_STRUCTURE_FILTERS,
  ...ENERGY_FILTERS,
  ...MARKET_CONTEXT_FILTERS,
  ...TOP_LOSER_FILTERS,
  ...TOP_GAINER_FILTERS,
  ...LONG_AES_FILTERS,
  ...LONG_BEST_DNA_FILTERS,
  ...LONG_POST_FEE_10_FILTERS,
  ...SNIPER_LONG_FILTERS,
  ...POSITIVE_COMBO_FILTERS,
  ...ANTI_COMBO_FILTERS,
  ...WINNING_SETUP_FILTERS,
  ...SHADOW_POLICY_FILTERS,
  ...CANDIDATE_RUNNER_FILTERS,
  ...OUTCOME_FORENSICS_FILTERS,
  ...FEE_ADJUSTED_OUTCOME_FILTERS,
  ...TICK_MICROSTRUCTURE_FILTERS,
  ...TICK_OUTCOME_FILTERS,
];

// ─── REGISTRY LOOKUP ──────────────────────────────────────────────────────────

const _registryById = new Map(LONG_FILTER_REGISTRY.map(f => [f.id, f]));

export function getFilterById(id) {
  return _registryById.get(id) ?? null;
}

export function getFiltersByFamily(family) {
  return LONG_FILTER_REGISTRY.filter(f => f.family === family);
}

export function getEntryPredictiveFilters() {
  return LONG_FILTER_REGISTRY.filter(f => f.entryPredictive === true);
}

export function getFiltersByScope(scope) {
  return LONG_FILTER_REGISTRY.filter(f =>
    f.scope === scope || f.scope === LONG_SCOPE.ALL_LONGS
  );
}

export { LONG_FILTER_REGISTRY_VERSION };
